import Head from "next/head";
import Navbar from "../components/Navbar";
import FooterContainer from "../components/Footer";
import BannerImage from "../components/BannerImage";
import MovieRow from "../components/MovieRow";
import requests from "../middleware/Request";

export default function Home() {
  return (
    <>
      <Head>
        <title>VK Prime Video</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className="bg-[#0f171e] min-h-screen">
        <Navbar />
        <BannerImage />
        <MovieRow fetchUrl={requests.fetchOriginals} title={"New release movies"} />
        <MovieRow fetchUrl={requests.fetchTrending} title={"From world of DC at Rs.79"} />
        <MovieRow fetchUrl={requests.fetchRomance} title={"Romance movies"} />
        <MovieRow fetchUrl={requests.fetchComedy} title={"Kids and family movies"} />
        <MovieRow fetchUrl={requests.fetchHorror} title={"Drama movies"} />
        <MovieRow fetchUrl={requests.fetchAction} title={"Action movies"} />
        <MovieRow fetchUrl={requests.fetchDocumentaries} title={"Science fiction movies"} />
        <FooterContainer />
      </main>
    </>
  );
}
