import Head from "next/head";
import Navbar from "../components/Navbar";
import Carousel from "../components/Carousel";
import BannerImage from "../components/BannerImage";
import NewRelease from "../components/NewRelease";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#0f171e] min-h-screen">
        <Navbar />
        <BannerImage />
        <NewRelease />
      </main>
    </>
  );
}
